name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/mini-erp
            git pull origin master
            composer install --no-dev --optimize-autoloader --prefer-dist
            npm install && npm run build
            php artisan route:clear && php artisan config:clear && php artisan view:clear && php artisan cache:clear
