name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/mini-erp
            sudo -u ec2-user git reset --hard origin/master
            sudo -u ec2-user git pull origin master
            sudo -u ec2-user composer install --no-dev --optimize-autoloader
            sudo -u ec2-user npm install
            sudo -u ec2-user npm run build
            sudo -u ec2-user php artisan config:cache
            sudo -u ec2-user php artisan route:cache
            sudo -u ec2-user php artisan view:clear
            sudo chown -R ec2-user:apache storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
